config/routes.rb
Rails.application.routes.draw do
  get '/movies' => 'movies#index'
  get '/movies/:id' => 'movies#show', as: :movie

  get '/actors' => 'actors#index'
  get '/actors/:id' => 'actors#show', as: :actor

  get 'signup'  => 'users#new'
  resources :users

  get '/login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  root 'movies#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :parts
  has_many :movies, through: :parts
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :parts
  has_many :actors, through: :parts
end

app/models/part.rb
class Part < ActiveRecord::Base
  belongs_to :movie
  belongs_to :actor
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find(params[:id])
    @movies = @actor.movies
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_user, only: [:index, :show]

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @actors = @movie.actors
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to 'login'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/index.html.erb
<div class="main actor-index">
  <div class="container">
    <div class="row">
      <% @actors.each do |actor| %>
          <div class="actor col-xs-2">
            <%= image_tag actor.image %>
            <h3><%= actor.first_name + " " + actor.last_name %></h3>
            <%= link_to "Learn more", actor_path(actor) %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/actors/show.html.erb
<div class="main actor-show">
  <div class="container">

    <!-- Display an actor's info here -->
    <div class="actor">
      <%= image_tag @actor.image %>
      <div class="info">
        <h3 class="actor-name"><%= @actor.first_name + " " + @actor.last_name  %></h3>
        <p class="actor-bio"><%= @actor.bio %></p>
      </div>
    </div>

    <h2>Movies</h2>
    <% @movies.each do |movie| %>
        <div class="movie">
          <%= image_tag movie.image %>
          <h3 class="movie-title"><%= movie.title %></h3>
          <p class="movie-release-year"><%= movie.release_year %></p>
          <p class="movie-plot"><%= movie.plot %></p>
        </div>
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="http://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css" rel="stylesheet" />
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,300' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <div class="container">
    <%= link_to root_path do %>
        <img src="http://s3.amazonaws.com/codecademy-content/courses/rails-auth/img/fotofoto-logo.svg" width="80" height="80"> &#12501; &#65387; &#12488; &#12501; &#65387; &#12488;
    <% end %>

    <div class="nav pull-right">
      <% if current_user %>
          <ul>
            <li><%= current_user.email %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
          </ul>
      <% else %>
          <ul>
            <li><%= link_to "Login", 'login' %></a></li>
            <li><%= link_to "Signup", 'signup' %></a></li>
          </ul>
      <% end %>

    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<div class="hero">
  <div class="container">
    <h2>Interstellar</h2>
    <p>Former NASA pilot Cooper (Matthew McConaughey) and a team of researchers travel across the galaxy to find out which of three planets could be mankind's new home.</p>
    <a href="#">Read More</a>
  </div>
</div>

<div class="main">
  <div class="container">
    <h2>Popular Films</h2>
    <% @movies.each do |movie| %>
        <div class="movie">
          <%= image_tag movie.image %>
          <h3><%= movie.title %></h3>
          <p><%= movie.release_year %></p>
          <p><%= movie.plot %></p>
          <%= link_to "Learn more", movie_path(movie) %>
        </div>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="main movie-show">
  <div class="container">
    <div class="movie">

      <!-- Display the movie's info here -->
      <div class="info">
        <%= image_tag @movie.image %>
        <h3 class="movie-title"><%= @movie.title %></h3>
        <p class="movie-release-year"><%= @movie.release_year %></p>
        <p class="movie-plot"><%= @movie.plot %></p>
      </div>
    </div>

    <h2>Cast</h2>
    <% @actors.each do |actor| %>
        <div class="actor">
          <%= image_tag actor.image %>
          <h3 class="actor-name"><%= actor.first_name %> <%= actor.last_name %></h3>
          <p class="actor-bio"><%= actor.bio %></p>
        </div>
    <% end %>
  </div>
</div>
Open

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

      <h1>Sign up</h1>

      <%= form_for(@user) do |f| %>
          <%= f.text_field :first_name, :placeholder => "First name" %>
          <%= f.text_field :last_name, :placeholder => "Last name" %>
          <%= f.email_field :email, :placeholder => "Email" %>
          <%= f.password_field :password, :placeholder => "Password" %>
          <%= f.submit "Create an account", class: "btn-submit" %>
      <% end %>


    </div>
  </div>
</div>